const state = {
  city: '',
  query: '',
  category: '',
  currentCategory: null,
  pagingURL: null,
  items: [],
  result: [],
  resultCopy: [],
  profilePosts: [],
  showModalImage: [],
  showModalInformation: [],
  showFullScreenLoader: false,
  showTagSection: false,
  postLoaderButton: false,
  showPaginigButton: false,
  showPagingButtonLoader: false,
  showProfileDetailsDialog: false,
  showProfileDetailsDialogMobile: false,
  showEmptyResultsAlert: false,
  showErrorConnectionAlert: false,
  proposedTags: [],
  numberOfTags: null,
};

export default state;
